### ISSUE TITLE
The pytorch can no run in mobile

### ISSUE THREAD

**Issue by dovanchan** [lizeng614/SqueezeNet-Neural-Style-Pytorch#1]
Hi:
    I think SqueezeNet is really a nice way to run fast-neural-network in mobile.
but the pytorch is not support the mobile runing.So I suggest you can try to implement it 
in Mxnet or Tensorflow.It will useful when someone want to run in mobile.This is my suggestion.

Thanks

**Comment by CoderInPajamas** [comment]
Hi dovanchan,
thank you for the advice. I think it's a good idea and I will think about it.

**Comment by dovanchan** [comment]
Really appreciate you agree with me and I will keep attention on your project.Thank you
